### PR TITLE
Fix broken poi:locate rake task

### LINKED ISSUE #444: Running `bundle exec rake poi:locate` fails on staging and locally
At the moment running `RAILS_ENV=staging bundle exec rake poi:locate` manually and directly on the staging and locally fails.

**Error output on staging server**
```
xxx@xxxx:/var/apps/wheelmap/staging/current$ RAILS_ENV=staging bundle exec rake poi:locate
rake aborted!
NoMethodError: undefined method `grenze' for [:conditions, {:parent_id=>nil}]:Array
/var/apps/wheelmap/staging/releases/hidden_number/lib/poi_locator.rb:114:in `block in load_regions'
/var/apps/wheelmap/staging/releases/hidden_number/lib/poi_locator.rb:111:in `each'
/var/apps/wheelmap/staging/releases/hidden_number/lib/poi_locator.rb:111:in `load_regions'
/var/apps/wheelmap/staging/releases/hidden_number/lib/poi_locator.rb:14:in `initialize'
/var/apps/wheelmap/staging/releases/hidden_number/lib/tasks/poilocator.rake:7:in `new'
/var/apps/wheelmap/staging/releases/hidden_number/lib/tasks/poilocator.rake:7:in `block (2 levels) in <top (required)>'
Tasks: TOP => poi:locate
```

Christoph wrote:
>Looks like the DB schema is not up2date

----

**Error output locally (on a separate & master branch)**
```
vagrant@wheelmap:~/wheelmap$ RAILS_ENV=development bundle exec rake poi:locate
rake aborted!
NameError: uninitialized constant RGeo::Geos::Factory
/home/vagrant/wheelmap/lib/poi_locator.rb:12:in `initialize'
/home/vagrant/wheelmap/lib/tasks/poilocator.rake:7:in `new'
/home/vagrant/wheelmap/lib/tasks/poilocator.rake:7:in `block (2 levels) in <top (required)>'
Tasks: TOP => poi:locate
(See full trace by running task with --trace)
```

### PR DESCRIPTION
**Pull request by schultyy**
This task was not working because it used deprecated ActiveRecord query methods which have been removed after Rails 4.0.

This resolves #444.

### CODE REVIEW

**Comment by 1000miles** [comment]
Thanks for the PR! 🚀 Merged. 

My best,
Thuy

File: lib/poi_locator.rb [hunk 1]
```diff
@@ -24,7 +24,7 @@ def run
     end
 
     lowest_id = Poi.lowest_id
-    Poi.find_in_batches(:conditions => {:region_id => @parent_id }, :start => lowest_id) do |batch|
+    Poi.where(region_id: @parent_id).find_in_batches(:start => lowest_id) do |batch|
```
Comment (christoph-buente) [inline lib/poi_locator.rb]: `:start => lowest_id` could have been converted to new hash syntax too:
`start: lowest_id`

Comment (1000miles) [inline lib/poi_locator.rb]: Thank you for the feedback, Christoph. :) We realized there are a lot of other parts in this project that still uses the old hash syntax, so maybe it makes sense to refactor this in a row in the future?

Comment (christoph-buente) [inline lib/poi_locator.rb]: Of course there is, and i apoligize for it. But the same line of code :)
