### PR TITLE
Fix toilet unknown bug

### LINKED ISSUE #492: bug: "toilets:wheelchair=unknown" written to OSM
- I am logged in as holgerd and use https://wheelmap.org/en/nodes/new/ to add the new node "Labyrintoom" to Wheelmap/OSM with wheelchair=no and no more info to the toilet, leaving it at "unknown" like this:

image

- I expect that only wheelchair=no is written to the node in OSM
- Instead, I also see toilets:wheelchair=unknown in the node: http://www.openstreetmap.org/node/4531573193 .
image

 I also see that there are thousands of tags like this in OSM: https://taginfo.openstreetmap.org/tags/toilets%3Awheelchair=unknown#overview (maybe all added this way?)

### PR DESCRIPTION
**Pull request by schultyy**
Resolves #492 

This prevents that unknown toilet status is being transmitted to Openstreetmap. This is already in place for the wheelchair status.

### CODE REVIEW

File: app/jobs/create_node_job.rb [hunk 1]
```diff
@@ -8,7 +10,8 @@ def self.enqueue(lat, lon, tags, user, source)
     return unless Rails.env.production? || Rails.env.test?
 
     # Remove wheelchair tag if value is "unknown"
-    tags.delete("wheelchair") if tags["wheelchair"] == 'unknown'
+    tags.delete(WHEELCHAIR_TAG_KEY) if tags[WHEELCHAIR_TAG_KEY] == 'unknown'
+    tags.delete(WHEELCHAIR_TOILET_TAG_KEY) if tags[WHEELCHAIR_TOILET_TAG_KEY] == "unknown"
```
Comment (Hoverbear) [inline app/jobs/create_node_job.rb]: Please use consistent quotes for both. :)

Comment (Hoverbear) [inline app/jobs/create_node_job.rb]: Please use consistent quotes for both. :)

File: spec/jobs/create_node_job_spec.rb [hunk 2]
```diff
@@ -85,7 +85,7 @@
   context "unknown value" do
 
     subject {
-      CreateNodeJob.enqueue(52.4, 13.0, { 'wheelchair' => 'unknown', 'amenity' => 'bar', 'name' => 'White horse' }, user, 'create_iphone')
+      CreateNodeJob.enqueue(52.4, 13.0, { 'wheelchair' => 'unknown', 'toilets:wheelchair' => 'unknown', 'amenity' => 'bar', 'name' => 'White horse' }, user, 'create_iphone')
     }
 
     it "does not save wheelchair tag" do
```
Comment (1000miles) [inline spec/jobs/create_node_job_spec.rb]: Since we are using only one test case here, can you please adjust the test case description which also includes `wheelchair:toilet tag`?
