### PR TITLE
Gather additional support form data

### LINKED ISSUE #370: Add user infos to bug reports (mailto:)
As a community supporter I want to have additional user infos when receiving a bug report via email, so I can help the user much faster.
- user clicks "report bug" (does not exist yet)
- new email opens (mailto:) 
- starting text: 'please describe info here but only in German or English please'
- the mail is also pre-filled with additional info:
  - operating system
  - browser version
  - is user logged in?
    - user name
    - OSM connected?
      - OSM-URL of user page
  - current zoom level
  - current lat/long of map
  - language
  - filter status of map (status or categories or WC enabled/disabled)
- user adds his/her problem description to this email and clicks send.

### PR DESCRIPTION
**Pull request by schultyy**
Follow up for #370 
Also resolves #370 

This gathers all missing data from a user:

- Latitude
- Longitude
- Last zoom level
- selected wheelchair filters
- selected toilet filters
- selected categories

These information are read from the user's cookie. This means if the user configured their browser to not have cookies we cannot get these information.

### CODE REVIEW

File: app/controllers/community_support_controller.rb [hunk 1]
```diff
@@ -26,6 +32,36 @@ def create
...
+
+  def longitude
+    request.cookies['last_lon']
+  end
+
+  def zoom_level
+    request.cookies['last_zoom']
+  end
+
+  def status_filters
```
Comment (1000miles) [inline app/controllers/community_support_controller.rb]: Does it make sense to call this method `wheelchair_status_filters` to be more precise?

File: app/controllers/community_support_controller.rb [hunk 2]
```diff
@@ -8,7 +8,13 @@ def new
   end
 
   def create
-    support_params = form_params.merge(user_agent: request.user_agent)
+    support_params = form_params.merge(user_agent: request.user_agent,
+                                       latitude: latitude,
+                                       longitude: longitude,
+                                       last_zoom_level: zoom_level,
+                                       status_filters: status_filters,
```
Comment (1000miles) [inline app/controllers/community_support_controller.rb]: As previously mentioned pls consider to rename `status_filters` to `wheelchair_status_filters`.

File: app/models/community_support_request.rb [hunk 3]
```diff
@@ -1,6 +1,7 @@
 class CommunitySupportRequest
   include ActiveModel::Validations
-  attr_accessor :name, :email, :message, :osm_username, :is_logged_in
+  attr_accessor :name, :email, :message, :osm_username, :is_logged_in,
+    :last_zoom_level, :latitude, :longitude, :status_filters, :category_filters, :toilet_filters
```
Comment (1000miles) [inline app/models/community_support_request.rb]: As previously mentioned pls consider to rename `:status_filters` to `:wheelchair_status_filters`.

**Comment by 1000miles** [comment]
LGTM
